[platformio]
default_envs = featheresp32v2

[env:featheresp32v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv
lib_deps =
  ; sparkfun/SparkFun Spectral Triad AS7265X  ; Using local patched version in lib/
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
